DROP SCHEMA IF EXISTS service;

CREATE SCHEMA service;

CREATE TABLE service.users
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(30)                              NOT NULL,
    last_name   VARCHAR(50)                              NOT NULL,
    password    VARCHAR(255)                             NOT NULL,
    email       VARCHAR(100)                             NOT NULL,
    role        VARCHAR(30),
    create_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE service.services
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                             NOT NULL,
    description VARCHAR(255)                             NOT NULL,
    price       DOUBLE PRECISION,
    user_id     INTEGER,
    create_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_services PRIMARY KEY (id)
);

ALTER TABLE service.services
    ADD CONSTRAINT FK_SERVICES_ON_USER FOREIGN KEY (user_id) REFERENCES service.users (id);

CREATE TABLE service.orders
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_status VARCHAR(255),
    order_date   TIMESTAMP WITHOUT TIME ZONE,
    price        DOUBLE PRECISION,
    create_date  TIMESTAMP WITHOUT TIME ZONE,
    update_date  TIMESTAMP WITHOUT TIME ZONE,
    user_id      INTEGER,
    service_id   INTEGER,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE service.orders
    ADD CONSTRAINT FK_ORDERS_ON_SERVICE FOREIGN KEY (service_id) REFERENCES service.services (id);

ALTER TABLE service.orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES service.users (id);